# Codecov configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "60...90"

  status:
    project:
      default:
        target: auto
        threshold: 2%
        informational: true
    patch:
      default:
        target: 70%
        threshold: 5%
        informational: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

ignore:
  - "**/tests/**"
  - "**/benches/**"
  - "crates/bindings/python/**"
  - "crates/bindings/node/**"
  - "crates/bindings/wasm/**"
  - "crates/bindings/go/**"
  - "**/build.rs"
  - "scripts/**"
  - "docs/**"
  - "examples/**"

# Per-crate component tracking
component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        informational: true
  individual_components:
    - component_id: grafeo-common
      name: Common (types, allocators, hashing)
      paths:
        - crates/common/src/**
    - component_id: grafeo-core
      name: Core (storage, indexes, execution)
      paths:
        - crates/core/src/**
    - component_id: grafeo-adapters
      name: Adapters (parsers, algorithms, plugins)
      paths:
        - crates/adapters/src/**
    - component_id: grafeo-engine
      name: Engine (database, sessions, transactions)
      paths:
        - crates/engine/src/**
