name: Feature Request
description: Suggest a new feature for Grafeo
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      description: Describe the feature and the problem it solves.
      placeholder: It would be useful to...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any extra details, examples, or alternatives you've considered.
    validations:
      required: false
