// TypeScript definitions for @grafeo-db/wasm
// These are auto-generated by wasm-pack during build.
// The declarations below are a reference for the expected API.

/**
 * Initialize the WASM module. Must be called before using any other API.
 */
export default function init(): Promise<void>;

/**
 * A Grafeo graph database instance running in WebAssembly.
 *
 * All data is held in memory within the WASM heap. For persistence,
 * use `exportSnapshot()` / `importSnapshot()` with IndexedDB or
 * the higher-level `@grafeo-db/web` package.
 */
export class Database {
  /** Creates a new in-memory database. */
  constructor();

  /**
   * Executes a GQL query and returns results as an array of objects.
   *
   * Each row becomes a JavaScript object with column names as keys.
   *
   * @example
   * ```js
   * const results = db.execute("MATCH (p:Person) RETURN p.name, p.age");
   * // [{name: "Alice", age: 30}, {name: "Bob", age: 25}]
   * ```
   */
  execute(query: string): Record<string, unknown>[];

  /**
   * Executes a GQL query and returns raw columns, rows, and metadata.
   *
   * @returns `{ columns: string[], rows: unknown[][], executionTimeMs?: number }`
   */
  executeRaw(query: string): {
    columns: string[];
    rows: unknown[][];
    executionTimeMs?: number;
  };

  /** Returns the number of nodes in the database. */
  nodeCount(): number;

  /** Returns the number of edges in the database. */
  edgeCount(): number;

  /** Returns the Grafeo version. */
  static version(): string;

  /** Frees the database from WASM memory. */
  free(): void;
}
